// Generated by https://quicktype.io
import {Artist} from './Artist.model';

export interface ArtistResponse {
  topartists: Topartists;
}

export interface Topartists {
  artist: Artist[];
  '@attr': ArtistAttr;
}

export interface ArtistAttr {
  country?: string;
  page: string;
  perPage?: string;
  totalPages: string;
  total?: string;
}
